trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli --force
    npm install --force
    npm run lint
    ng build 
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@0
  displayName: 'Publish pipeline artifact'
  inputs:
    artifactName: 'drop'
    targetPath: '$(Build.ArtifactStagingDirectory)'

- powershell: |
    $sourcePath = "$(Build.ArtifactStagingDirectory)\dist"
    $destinationPath = "C:\azagent\A2"

    # Create the destination directory if it doesn't exist
    New-Item -Path $destinationPath -ItemType Directory -Force

    # Copy the files from source to destination
    Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force
  displayName: 'Copy dist to C:\azagent\A2'
