trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli --force
    npm install --force
    npm run lint
    ng build 
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.SourcesDirectory)/dist   # Change the path to the "dist" directory
    artifactName: drop
    publishLocation: Container
