trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
    displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli --force
    npm install --force
    npm run lint
    ng build 
  displayName: 'npm install and build'

- powershell: |
    $sourcePath = "$(System.DefaultWorkingDirectory)\dist"  # Use the correct source path
    $destinationPath = "C:\azagent\A2"

    # Verify if the source directory exists
    if (Test-Path -Path $sourcePath -PathType Container) {
        # Create the destination directory if it doesn't exist
        New-Item -Path $destinationPath -ItemType Directory -Force

        # Copy the files from source to destination
        Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force
    } else {
        Write-Host "Source directory '$sourcePath' does not exist."
    }
  displayName: 'Copy dist to C:\azagent\A2'
