name: Build and deploy Node.js app to Azure Web App - portalimsdev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install --force
          npm run build --if-present
          npm run test --if-present
      
      - name: Create zip archive
        run: |
          # Install zip utility
          sudo apt-get install zip -y
          # Create zip archive of current directory
          zip -r node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: node-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DD1C497DBC8D415DA9AD6D85D54BBAF1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B85CECB13B8D44848F159C43EEFFBCC2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9FBAE3DADD43460EA3EEF5123FE6D934 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'portalimsdev'
          slot-name: 'Production'
          package: ${{ github.workspace }}/node-app.zip
